seed: 314176
device: cuda:0
num_workers: 0 #!eval "__import__('os') or os.cpu_count()"

batch_size: 128

tik_alpha: 0.1

batch_acc: 1
ckpt: ""
lr: 0.0001
weight_decay: 0.01
intern_lr: 0.001
epochs: 350
intern_iterations: 8

adv_lr: 1e0
adv_iterations: 10
adv_epsilon: 1.0